services:
  app:
    image: anhductk74/taskmanagement_backend:latest
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_taskmanagement
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: developer_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: redis_password
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_taskmanagement
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer_password
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p123456']
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: redis_password
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: [ 'redis-server', '--requirepass', 'redis_password' ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redis_password", "--raw", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
  redis_data:
